server:
  port: 8888
spring:
  application:
    name: config-client
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prabasingaravel/cloud-config
        bootstrap: true
management:
  endpoints:
    web:
      exposure:
        include: "*"